### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by tangfei67** [lt94/Weather#1]
你怎么也写安卓了？是一直都在写吗？

建议跟项目无关，就是上传到git的东西，最好不要带上bin目录下生成的那些文件，譬如class等，其他的不相关的也可以去掉。

**Comment by lt94** [comment]
好的~~一直都再写啊~~跟小伙伴接了点私活，所以现在练练手

**Comment by tangfei67** [comment]
@lt94 厉害，膜拜！

**Comment by lt94** [comment]
为啥不能把生成文件上传了？
